apiVersion: v1
kind: ConfigMap
metadata:
  name: firewall-rules
  namespace: default
data:
  rules.yaml: |
    rules:
      - name: "allow-http"
        action: ALLOW
        protocol: TCP
        port: 8080
        description: "Allow HTTP traffic"
      - name: "allow-https"
        action: ALLOW
        protocol: TCP
        port: 8443
        description: "Allow HTTPS traffic"
      - name: "allow-dns"
        action: ALLOW
        protocol: UDP
        port: 53
        description: "Allow DNS queries"
      - name: "allow-icmp"
        action: ALLOW
        protocol: ICMP
        description: "Allow ping/ICMP"
      - name: "block-ssh"
        action: BLOCK
        protocol: TCP
        port: 22
        description: "Block SSH access"
      - name: "block-telnet"
        action: BLOCK
        protocol: TCP
        port: 23
        description: "Block Telnet access"
      - name: "default-allow"
        action: ALLOW
        protocol: "*"
        port: "*"
        description: "Default allow rule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsm-firewall
  namespace: default
  labels:
    app: nsm-firewall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsm-firewall
  template:
    metadata:
      labels:
        app: nsm-firewall
    spec:
      containers:
      - name: firewall
        image: networkservicemesh/cmd-nse-firewall:v1.14.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_NAME
          value: "firewall-service"
        - name: NSM_LABELS
          value: "app=firewall"
        - name: NSM_RULES_CONFIG_PATH
          value: "/etc/firewall/rules.yaml"
        - name: NSM_LOG_LEVEL
          value: "INFO"
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: firewall-rules
          mountPath: /etc/firewall
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
      - name: firewall-rules
        configMap:
          name: firewall-rules
---
apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: firewall-service
  namespace: default
spec:
  payload: ETHERNET
  matches:
  - sourceSelector:
      app: client
    destinationSelector:
      app: server
    routes:
    - name: firewall
      match:
        sourceSelector:
          app: client
        destinationSelector:
          app: server
