---
apiVersion: v1
kind: Pod
metadata:
  name: tunnel-server
  labels:
    app: tunnel-server
  annotations:
    networkservicemesh.io: kernel://secure-tunnel/nsm-1?ip=172.16.4.20/24
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
