---
apiVersion: v1
kind: Pod
metadata:
  name: opa-client
  labels:
    app: opa-client
  annotations:
    networkservicemesh.io: kernel://opa-service/nsm-1?ip=172.16.5.10/24
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "apk add --no-cache curl && trap : TERM INT; sleep infinity & wait"]
