---
apiVersion: v1
kind: Pod
metadata:
  name: opa-server
  labels:
    app: opa-server
  annotations:
    networkservicemesh.io: kernel://opa-service/nsm-1?ip=172.16.5.20/24
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  - name: opa
    image: openpolicyagent/opa:latest
    ports:
    - containerPort: 8181
    args:
    - "run"
    - "--server"
    - "--addr=0.0.0.0:8181"
    - "/policies"
    volumeMounts:
    - name: opa-policy
      mountPath: /policies
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 8080
    command: ["/bin/sh"]
    args:
    - -c
    - |
      mkdir -p /usr/share/nginx/html/public /usr/share/nginx/html/admin /usr/share/nginx/html/hr
      echo "Public Information" > /usr/share/nginx/html/public/info
      echo "Admin Users List" > /usr/share/nginx/html/admin/users
      echo "HR Salary Data" > /usr/share/nginx/html/hr/salaries
      sed -i 's/listen       80/listen       8080/' /etc/nginx/conf.d/default.conf
      nginx -g 'daemon off;'
  volumes:
  - name: nginx-config
    configMap:
      name: opa-config
  - name: opa-policy
    configMap:
      name: opa-policy
