---
apiVersion: v1
kind: Pod
metadata:
  name: client-b
  labels:
    app: client-b
  annotations:
    networkservicemesh.io: kernel://vwire/nsm-1?ip=172.16.2.2/24
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
