---
apiVersion: v1
kind: Pod
metadata:
  name: dns-client
  labels:
    app: dns-client
  annotations:
    networkservicemesh.io: kernel://dns-service/nsm-1?ip=172.16.3.10/24
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "apk add --no-cache bind-tools && trap : TERM INT; sleep infinity & wait"]
